<?php
/** @var \Quiz\Entity\Quiz $quiz */
?>

<div class="row">

    <div class="col-md-4">
        <h2><?php echo $quiz->getName(); ?></h2>
        <?php if (null != $quiz->getCopyOfQuiz()): ?>
            <h3>(kopie: <?php echo $quiz->getCopyOfQuiz()->getName(); ?>)</h3>
        <?php endif ?>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <strong>
                    Plaats:
                </strong>
            </div>
            <div class="col-md-6 col-xs-6">
                <?php echo $quiz->getLocation(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <strong>
                    Datum:
                </strong>
            </div>
            <div class="col-md-6 col-xs-6">
                <?php echo $quiz->getDate()->format('d-m-Y H:i:s'); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <strong>
                    Aantal rondes:
                </strong>
            </div>
            <div class="col-md-6 col-xs-6">
                <?php echo $quiz->getNumberOfRounds(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <strong>
                    Aantal vragen:
                </strong>
            </div>
            <div class="col-md-6 col-xs-6">
                <?php echo $quiz->getMaxNumberOfQuestions(); ?>
                (<?php echo $quiz->getNumberOfQuestions(); ?> gevuld)
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <strong>
                    Totaal aantal punten:
                </strong>
            </div>
            <div class="col-md-6 col-xs-6">
                <?php echo $quiz->getTotalPoints(); ?>
            </div>
        </div>

        <br />
        <?php foreach($quiz->getQuizRounds() as $quizRound): ?>
            <div class="row">
                <div class="col-md-6">
                    <a href="#round<?php echo $quizRound->getId(); ?>">
                        Ronde <?php echo $quizRound->getNumber(); ?>
                    </a>
                </div>
                <div class="col-md-6 text-right">
                    <div class="progress">
                        <?php
                            $maxQuestions = $quizRound->getMaxNumberOfQuestions();
                            $nrOfQuestions = $quizRound->getNumberOfQuestions();
                            $percentage = round($nrOfQuestions/$maxQuestions * 100);
                            $class = '';
                            if ($percentage < 50) {
                                $class = 'progress-bar-danger';
                            } elseif ($percentage < 70) {
                                $class = 'progress-bar-warning';
                            } elseif ($percentage < 100) {
                                $class = 'progress-bar-info';
                            } else {
                                $class = 'progress-bar-success';
                            }
                        ?>
                        <div class="progress-bar <?php echo $class; ?>" role="progressbar"
                             aria-valuenow="<?php echo $percentage; ?>"
                             aria-valuemin="0" aria-valuemax="100"
                             style="width: <?php echo $percentage; ?>%;">
                            <?php echo $percentage; ?>%
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>

    </div>
    <div class="col-md-8">
        <canvas id="pieChart" width="500" height="500"></canvas>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <a href="<?php echo $this->url('quiz/detail/print-questions', ['quizId' => $quiz->getId()]); ?>" target="_blank">
            <button class="btn btn-info">
                <i class="fa fa-file-text-o"></i>
                 Vragen printen
            </button>
        </a>
    </div>
    <div class="col-md-2">
        <a href="<?php echo $this->url('quiz/detail/print-answers', ['quizId' => $quiz->getId()]); ?>" target="_blank">
            <button class="btn btn-success">
                <i class="fa fa-file-text-o"></i>
                Antwoorden printen
            </button>
        </a>
    </div>
    <div class="col-md-2">
        <a href="<?php echo $this->url('quiz/detail/print-photos', ['quizId' => $quiz->getId()]); ?>" target="_blank">
            <button class="btn btn-primary">
                <i class="fa fa-file-text-o"></i>
                Foto ronde printen
            </button>
        </a>
    </div>
</div>

<div>
    <?php foreach ($quiz->getQuizRounds() as $quizRound): ?>
        <h2 id="round<?php echo $quizRound->getId(); ?>">
            Ronde <?php echo $quizRound->getNumber(); ?>
            <?php if ($quizRound->getTheme() != ""): ?>
             (<?php echo $quizRound->getTheme(); ?>)
            <?php endif ?>
            <?php if ($quizRound->hasAudio()): ?>
                <a href="<?php echo $this->url('download-mp3-round', ['quizRoundId' => $quizRound->getId()]); ?>"><i class="fa fa-download" ></i></a>
            <?php endif ?>
        </h2>
        <ol class="list-group sortable">
            <?php foreach ($quizRound->getQuizRoundQuestions() as $quizRoundQuestion): ?>
                    <li class="list-group-item" data-quizquestionid="<?php echo $quizRoundQuestion->getId(); ?>"
                        title="<?php echo $quizRoundQuestion->getQuestion()->getAnswer(); ?>">
                        <span class="<?php echo $quizRoundQuestion->getQuestion()->getCategory()->getIcon(); ?>"></span>
                        <?php echo $quizRoundQuestion->getQuestion()->getQuestion(); ?>
                        <?php if ($quizRoundQuestion->getQuestion()->hasImage()): ?>
                            <span class="label label-primary label-as-badge">
                                    <i class="fa fa-image"></i>
                            </span>
                        <?php endif ?>
                        <?php if ($quizRoundQuestion->getQuestion()->hasAudio()): ?>
                            <audio controls src="data:audio/ogg;base64,<?php echo $quizRoundQuestion->getQuestion()->getAudio(); ?>" style="width: 150px"></audio>
                        <?php endif ?>
                        <span class="pull-right">
                            <a href="<?php echo $this->url('quiz/remove-question', ['quizRoundQuestionId' => $quizRoundQuestion->getId()]); ?>" style="color: #ff0000">
                                <i class="fa fa-close"></i>
                            </a>
                        </span>
                        <a class="pull-right" style="margin-right: 10px;" href="<?php echo $this->url('comment', ['quizRoundQuestionId' => $quizRoundQuestion->getId()]); ?>">
                            <i class="fa fa-comments-o"></i>
                            <?php if ($quizRoundQuestion->getComments()->count() > 0): ?>
                                <span class="badge badge-warning">
                                    <?php echo $quizRoundQuestion->getComments()->count(); ?>
                                </span>
                            <?php endif ?>
                        </a>
                        <?php if ($quizRoundQuestion->getQuestion()->hasAudio()): ?>
                            <span class="pull-right" style="margin-right: 10px;">
                                <a href="<?php echo $this->url('download-mp3', ['questionId' => $quizRoundQuestion->getQuestion()->getId()]); ?>"><i class="fa fa-download"></i></a>
                            </span>
                        <?php endif ?>
                    </li>
            <?php endforeach ?>
        </ol>
    <?php endforeach ?>
    <h4>Quiz mutaties</h4>
    <?php foreach($quiz->getQuizLogs() as $quizLog): ?>
        <?php
            $createdDate = new DateTime($quizLog->getDateCreated()->format('Y-m-d H:i:s'), new DateTimeZone('UTC'));
            $dateAgo = new \Smirik\PHPDateTimeAgo\DateTimeAgo();
            $dateAgo->setTextTranslator(new \Quiz\PHPDateTimeAgo\TextTranslator\DutchTranslator());
        ?>
        <div class="row">
            <div class="pull-left">
                <i class="<?php echo $quizLog->getIcon(); ?>"></i>
            </div>
            <div class="col-md-2">
                <?php echo $dateAgo->get($createdDate->setTimezone(new DateTimeZone('Europe/Amsterdam'))); ?>
            </div>
            <div class="col-md-9 pull-left">
                <?php echo $quizLog->getText(); ?>
            </div>
        </div>
    <?php endforeach ?>
</div>

<!-- Modal -->
<!--<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">-->
<!--    <div class="modal-dialog">-->
<!--        <div class="modal-content">-->
<!--            <div class="modal-header">-->
<!--                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>-->
<!--                <h4 class="modal-title" id="myModalLabel">Modal title</h4>-->
<!--            </div>-->
<!--            <div class="modal-body">-->
<!--                ...-->
<!--            </div>-->
<!--            <div class="modal-footer">-->
<!--                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
<!--                <button type="button" class="btn btn-primary">Save changes</button>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<script type="text/javascript">
    $(document).ready(function(){
        $(".sortable").sortable({
            update:  function (event, ui) {
                var id = $(ui.item).data('quizquestionid');
                var newPos = ui.item.index() + 1;
                $.ajax({
                    url:"/reset-quiz-round-question-number/" + id + "/" + newPos
                });
            }
        });
    });
</script>

<script type="text/javascript">
    var data = {
        labels: ["<?php echo implode('", "', $labels); ?>"],
        datasets: [
            {
                label: "Categorie verhouding",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: [<?php echo implode(', ', $data); ?>]
            },
        ]
    }

    var options = {

    }

    window.onload = function(){
        var ctx = document.getElementById("pieChart").getContext("2d");
        //var myPieChart = new Chart(ctx[0]).Pie(data,options);
        window.myLine = new Chart(ctx).Radar(data, options);;
    }

</script>