<?php
/** @var \Quiz\Entity\Quiz[] $quizzes */
?>

<div class="row">
    <div class="col-md-6">
        <div class="col-md-2">
            <a href="<?php echo $this->url('quiz/form'); ?>">
                <button class="btn btn-success">
                    <i class="fa fa-file-text-o"></i>
                    Nieuwe Quiz
                </button>
            </a>
        </div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Naam</th>
                <th>Locatie</th>
                <th>Datum</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($quizzes as $quiz): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('quiz/detail', ['quizId' => $quiz->getId()]); ?>">
                            <?php echo $quiz->getName(); ?>
                        </a>
                    </td>
                    <td>
                        <?php echo $quiz->getLocation(); ?>
                    </td>
                    <td>
                        <?php echo $quiz->getDate()->format('d-m-Y H:i:s'); ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>