<?php
/** @var \Quiz\Entity\Quiz $quiz */

$escape = new Zend\Escaper\Escaper();
?>
<div class="book">
    <div class="page">
        <div class="subpage">
            <div style="font-size: 60px; margin-top: 80px;text-align: center">
                <?php echo $escape->escapeHtml($quiz->getName()); ?>
            </div>
            <div style="text-align: center">
                <?php echo $escape->escapeHtml($quiz->getDate()->format('l j F Y')); ?>
            </div>
            <div style="text-align: center">
                <?php echo $escape->escapeHtml($quiz->getDate()->format('H:i')); ?>
            </div>
            <div style="font-size: 60px; margin-top: 150px; text-decoration: underline; text-align: center">
                Antwoorden
            </div>
        </div>
    </div>
    <?php for($i=0; $i < ceil($quiz->getNumberOfRounds() / 2); $i++): ?>
        <div class="page">
            <div class="subpage">
                <?php for ($j=0; $j < 2; $j++): ?>
                    <?php
                    $quizRound = $quiz->getNextRound();
                    if (!$quizRound) {
                        break;
                    }
                    ?>
                    <h1>
                        Ronde <?php echo $quizRound->getNumber(); ?>
                        <?php if ($quizRound->getTheme() != ""): ?>
                            (<?php echo $quizRound->getTheme(); ?>)
                        <?php endif ?>
                    </h1>
                    <ol>
                        <?php foreach($quizRound->getQuizRoundQuestions() as $quizQuestion): ?>
                            <li>
                                <?php echo $quizQuestion->getQuestion()->getAnswer(); ?>
                                <?php if ($quizQuestion->getQuestion()->getPoints() > 1): ?>
                                    <strong>
                                        [<?php echo $quizQuestion->getQuestion()->getPoints();?>pt]
                                    </strong>
                                <?php endif ?>
                                <br />
                                <small style="font-size: 6pt">
                                    <?php echo $quizQuestion->getQuestion()->getQuestion(); ?>
                                </small>
                            </li>
                        <?php endforeach ?>
                    </ol>
                <?php endfor ?>
            </div>
        </div>
    <?php endfor ?>
</div>