<?php
/** @var \Quiz\Entity\User $user */
/** @var \Quiz\Entity\Question[] $questions */
/** @var \Quiz\Entity\Quiz[] $futureQuizzes  */

$escape = new Zend\Escaper\Escaper('utf-8');
?>
<div class="row">
    <div>
        <table class="table table-striped" border="0">
            <tbody>
            <?php foreach ($questions as $question): ?>
                <tr>
                    <td>
                        <span class="<?php echo $question->getCategory()->getIcon(); ?>"></span>
                    </td>
                    <td>
                        <div class="row" style="margin-left: 0px">
                            <a href="<?php echo $this->url('question/detail', ['questionId' => $question->getId()]); ?>"
                                title="<?php echo $question->getAnswer(); ?>">
                                <?php echo $escape->escapeHtml($question->getQuestion()); ?>
                            </a>
                        </div>
                        <div class="row">
                            <?php foreach ($question->getQuestionTags() as $questionTag): ?>
                                <div class="badge">
                                    <?php echo $escape->escapeHtml($questionTag->getTag()->getName()); ?>
                                </div>
                            <?php endforeach ?>
                        </div>
                        <span>
                            <small>
                                <?php echo $question->getCreatedBy()->getUsername(); ?>,
                                <?php echo $question->getDateCreated()->format('d-m-Y H:i:s'); ?>
                            </small>
                        </span>
                    </td>
                    <td class="text-right">
                        <?php if ($question->hasImage()): ?>
                            <span class="label label-primary label-as-badge">
                                <i class="fa fa-image"></i>
                            </span>
                        <?php endif ?>
                        <?php if ($question->isAudioQuestion()): ?>
                            <span class="label label-primary label-as-badge">
                                <i class="fa fa-music"></i>
                            </span>
                        <?php endif ?>
                        <?php if (!$question->hasSource()): ?>
                            <span class="label label-danger label-as-badge" title="Bron ontbreekt">
                                <i class="fa fa-unlink"></i>
                            </span>
                        <?php endif ?>
                        <?php if ($question->getQuestionLikes()->count() > 0): ?>
                            <span class="label label-success label-as-badge" title="Aantal likes">
                                <?php echo $question->getQuestionLikes()->count(); ?>
                                <i class="fa fa-thumbs-up"></i>
                            </span>
                        <?php endif ?>
                        <?php if ($question->getQuizRoundQuestions()->count() > 0): ?>
                            <?php
                                $locations = "";
                                foreach ($question->getQuizRoundQuestions() as $quizRoudQuestion) {
                                    $locations .= "(".
                                        $quizRoudQuestion->getQuizRound()->getQuiz()->getDate()->format('M-y').
                                        " ".
                                        $quizRoudQuestion->getQuizRound()->getQuiz()->getLocation().
                                        ")";
                                }
                            ?>
                            <span class="label label-warning label-as-badge" title="Gesteld: <?php echo $locations; ?>">
                                <?php echo $question->getQuizRoundQuestions()->count(); ?>
                                <i class="fa fa-microphone"></i>
                            </span>
                        <?php endif ?>
                        <!--                        <span class="label label-info label-as-badge">-->
                        <!--                            3-->
                        <!--                            <i class="fa fa-tags"></i>-->
                        <!--                        </span>-->
                    </td>
                    <td>
                        <!-- Edit button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <span class="fa fa-cogs"></span>
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li>
                                    <a href="<?php echo $this->url('question/form', [], ['query' => ['id' => $question->getId()]]); ?>">
                                        <span class="fa fa-pencil"></span>
                                        Aanpassen
                                    </a>
                                </li>
                                <?php if (!$question->userHasLiked($user)): ?>
                                    <li>
                                        <a href="<?php echo $this->url('question/like', ['questionId' => $question->getId()]); ?>">
                                            <span class="fa fa-thumbs-up"></span>
                                            Liken
                                        </a>
                                    </li>
                                <?php else: ?>
                                    <li>
                                        <a href="<?php echo $this->url('question/unlike', ['questionId' => $question->getId()]); ?>">
                                            <span class="fa fa-thumbs-down"></span>
                                            Unliken
                                        </a>
                                    </li>
                                <?php endif ?>
                                <?php foreach ($futureQuizzes as $quiz): ?>
                                    <?php if (!$quiz->containsQuestion($question)): ?>
                                        <li class="divider" />
                                        <?php foreach ($quiz->getQuizRounds() as $quizRound): ?>
                                            <?php if (!$quizRound->isFull()): ?>
                                                <li>
                                                    <a href="<?php echo $this->url('question/add-to-quiz-round',
                                                                                   [
                                                                                       'questionId' => $question->getId(),
                                                                                       'quizRoundId' => $quizRound->getId()
                                                                                   ]); ?>">
                                                        <span class="fa fa-plus"></span>
                                                        <?php echo $quiz->getName().
                                                            " - Ronde ".
                                                            $quizRound->getNumber().
                                                            " (".$quizRound->getPercentageFull()."%)"; ?>
                                                    </a>
                                                </li>
                                            <?php endif ?>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </ul>
                        </div>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>