<?php
/** @var \Quiz\Entity\ThemeRound[] $themeRounds */
?>
<div class="row">
    <div class="col-md-4">
        <table class="table">
            <thead>
            <tr>
                <th>Thema rondes</th>
                <th>
                    <a href="<?php echo $this->url('theme-rounds/form'); ?>">
                        <button class="btn btn-success">
                            <i class="fa fa-file-text-o"></i>
                            Nieuwe Thema ronde
                        </button>
                    </a>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($themeRounds as $themeRound): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('theme-rounds/detail', ["themeRoundId" => $themeRound->getId()]); ?>">
                            <?php echo $themeRound->getName(); ?>
                        </a>
                    </td>
                    <td>
                        <?php if ($themeRound->isAudio()): ?>
                            <span class="label label-primary label-as-badge">
                                <i class="fa fa-music"></i>
                            </span>
                        <?php endif ?>
                        <?php if ($themeRound->isPhoto()): ?>
                            <span class="label label-primary label-as-badge">
                                <i class="fa fa-image"></i>
                            </span>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>