<nav class="navbar navbar-quizis navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">
                QUIZIS
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Vragen <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('question'); ?>">Alle vragen</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Filter</li>
                        <li><a href="<?php echo $this->url('question/not-asked'); ?>">Niet eerder gesteld</a></li>
                        <li><a href="<?php echo $this->url('question/not-asked-vdo'); ?>">Niet eerder gesteld @ VDO</a></li>
                        <li><a href="<?php echo $this->url('question/image'); ?>">Met afbeeldingen</a></li>
                        <li><a href="<?php echo $this->url('question/audio'); ?>">Met audio</a></li>
                        <li><a href="<?php echo $this->url('question/music'); ?>">Met muziek</a></li>
                        <li><a href="<?php echo $this->url('question/most-asked'); ?>">Meest gesteld</a></li>
                        <li><a href="<?php echo $this->url('question/most-asked-year'); ?>">Meest gesteld (dit jaar)</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Inhoud <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('category'); ?>">Categorieën</a></li>
                        <li><a href="<?php echo $this->url('theme-rounds'); ?>">Thema Rondes</a></li>
                        <li><a href="<?php echo $this->url('tag'); ?>">Tags</a></li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('brainstorm'); ?>">Brainstorm</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Quizzen <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('quiz'); ?>">Alle quizzen</a></li>
                        <li><a href="<?php echo $this->url('quiz/next-quiz'); ?>">Volgende quiz</a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->url('customer'); ?>">Klanten</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><i class="fa fa-sign-out"></i> Uitloggen</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>