<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">
                #6 quiz admin system
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="<?php echo $this->url('question'); ?>">Vragen</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Filter <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('question/yours'); ?>">Vragen van jou</a></li>
                        <li><a href="<?php echo $this->url('question/liked'); ?>">Vragen door jou geliket</a></li>
                        <li><a href="<?php echo $this->url('question/likes'); ?>">Vragen met likes</a></li>
                        <li><a href="<?php echo $this->url('question/not-asked'); ?>">Vragen niet eerder gesteld</a></li>
                        <li><a href="<?php echo $this->url('question/no-source'); ?>">Vragen zonder bron</a></li>
                    </ul>
                </li>
                <li class="">
                    <a href="<?php echo $this->url('category'); ?>">Categorieën</a>
                </li>
<!--                <li class="">-->
<!--                    <a href="--><?php //echo $this->url('tag'); ?><!--">Tags</a>-->
<!--                </li>-->
                <li><a href="<?php echo $this->url('quiz'); ?>">Quizzen</a></li>
                <li><a href="<?php echo $this->url('quiz/next-quiz'); ?>">Volgende Quiz</a></li>
                <li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Uitloggen</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>