<?php
/** @var \Quiz\Form\Customer $form */

$form->setAttribute(
    'action',
    $this->url(
        'customer/form/process', [],
        [
            'query' => [
                'id' => $form->getObject()->getId()
            ]
        ]
    )
);

$this->form->prepare();
echo $this->form()->openTag($this->form);
echo $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
echo $this->form()->closeTag();
