<?php
/** @var \Quiz\Entity\Customer[] $customers */
?>

<a href="<?php echo $this->url('customer/form'); ?>" style="z-index: 1000; position: relative">
    <button type="button" class="btn btn-success">
        <i class="fa fa-plus"></i>
        Klant toevoegen
    </button>
</a>

<div class="row">
    <div class="col-md-10">
        <?php if (count($customers) > 0): ?>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Naam</th>
                    <th>Woonplaats</th>
                    <th>E-mailadres</th>
                    <th>Telefoonnummer</th>
                    <th>Contactpersoon</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($customers as $customer): ?>
                    <tr>
                        <td>
                            <?php echo $this->escapeHtml($customer->getName()); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($customer->getCity()); ?>
                        </td>
                        <td>
                            <?php if ($customer->getEmail()): ?>
                                <a href="mailto:<?php echo $this->escapeHtmlAttr($customer->getEmail()); ?>">
                                    <?php echo $this->escapeHtml($customer->getEmail()); ?>
                                </a>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($customer->getPhone()); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($customer->getContactPerson()); ?>
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <span class="fa fa-cogs"></span>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li>
                                        <a href="<?php echo $this->url('customer/form', [], ['query' => ['id' => $customer->getId()]]); ?>">
                                            <span class="fa fa-pencil"></span>
                                            Aanpassen
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        <?php else: ?>
            <p class="text-muted">Geen klanten gevonden.</p>
        <?php endif; ?>
    </div>
</div>
